baseURL = 'https://libreboot.runxiyu.org/'
languageCode = 'en-us'
title = 'Unofficial (Simplified) Libreboot Documentation'

[markup.goldmark.renderer]
unsafe = true

[markup.tableOfContents]
ordered = false
