#!/usr/bin/env bash
#
# Bash because $BASH_SOURCE is really useful.
#

set -x

cd "${BASH_SOURCE[0]%/*}"

hugo && rsync --chmod=u=rwX,go=rX --delete-after -rv public/ me@runxiyu.org:/var/www/libreboot/
